
### try...except
```python
try:
  要檢查的部分
  
except:
  新增異常和處理
```
| 錯誤資訊 | 說明 |
|:-------:|:----:|
| NameError |	使用沒有被定義的對象|
| IndexError |	索引值超過了序列的大小 |
| TypeError |	數據類型 ( type ) 錯誤 |
| SyntaxError |	Python 語法規則錯誤 |
| ValueError | 傳入值錯誤 |
| KeyboardInterrupt |	當程式被手動強制中止 |
| AssertionError |	程式 asset 後面的條件不成立 |
| KeyError |	鍵發生錯誤 |
| ZeroDivisionError |	除以 0 |
| AttributeError |	使用不存在的屬性 |
| IndentationError |	Python 語法錯誤 ( 沒有對齊 ) |
| IOError |	Input/output異常 |
| UnboundLocalError |	區域變數和全域變數發生重複或錯誤 |


範例:  
判斷輸入值是否為數字;是則繼續，否則強制跳出 ❮本次❯ 迴圈，繼續進入下一圈  
```python
number = 1
while (number !=0):
    try:
        number = input("please enter the number, enter 0 to exit : ")
        number = int(number)
    except ValueError:
        print("input not integer")
        continue
    if (number % 2 !=0):
        print("奇數")
    else :
        print("偶數")
```
